### ISSUE TITLE
How much does a decent map cost?

### ISSUE THREAD

**Issue by manik1235** [manik1235/story_time#29]
How much should we plan to spend on a map?

Should we find something open source/free?
Should we ask an artist friend?
Should we ask a non-friend artist?
Should we hope for more resources in the future and upgrade assets as we can later on?

**Comment by dreckmal** [comment]
I'm unsure on how to check. I'm not entirely sure if there is an 'industry standard'. I've always gotten the impression from actual artist friends that they pretty much come up with their own scale.

**Comment by manik1235** [comment]
Closing, we are going to use [Campaign Cartographer](https://www.profantasy.com/products/cc3.asp)
